# Generated by Django 5.0.6 on 2025-03-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Sensor', '0001_initial'),
    ]

    operations = [
    ]
