# Generated by Django 5.0.6 on 2025-03-16 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api_Sensor', '0002_auto_20250316_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_inicio', models.TimeField(auto_now_add=True)),
                ('hora_finalizacion', models.TimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.FloatField(default=0.0)),
                ('presion1', models.FloatField(default=0.0)),
                ('presion2', models.FloatField(default=0.0)),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_clave', to='Api_Sensor.experimento')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.FloatField(default=0.0)),
                ('presion1', models.FloatField(default=0.0)),
                ('presion2', models.FloatField(default=0.0)),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='Api_Sensor.experimento')),
            ],
        ),
    ]
