# Generated by Django 5.0.6 on 2025-03-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Sensor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
